### ISSUE TITLE
Implement a graph assistant with multiple agents for IBU insurance processing

### ISSUE THREAD

**Issue by AthenaDecisionSystems** [AthenaDecisionSystems/athena-owl-demos#4]
The first agent classify the user's query

The branches are INFORMATION, and  COMPLAINT

For the Complaint, tune the prompt to include RAG, and decision service tool

Have a Tool Action node so the graph implements a ReAct. 

The information Agent need Tavily and the vector store retriever as tools

**Comment by jbcodeforce** [comment]
Done with today commit
